version: "2"
services:
    www:
        build: .
        ports: 
            - "8003:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
volumes:
    persistent:
#stdin_open: true
#tty: true
